/**
 * Generates environment files and firebase-messaging-sw.js from .env variables.
 * Run: node scripts/set-env.js
 *
 * Reads from .env file (local dev) or process.env (CI/CD).
 */

const fs = require('fs');
const path = require('path');

// ---- Load .env if present ----
const envPath = path.resolve(__dirname, '..', '.env');
const env = {};

if (fs.existsSync(envPath)) {
  const lines = fs.readFileSync(envPath, 'utf-8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const idx = trimmed.indexOf('=');
    if (idx === -1) continue;
    const key = trimmed.substring(0, idx).trim();
    const value = trimmed.substring(idx + 1).trim();
    env[key] = value;
  }
}

function get(key) {
  return process.env[key] || env[key] || '';
}

// ---- Validate required vars ----
const required = [
  'FIREBASE_API_KEY', 'FIREBASE_AUTH_DOMAIN', 'FIREBASE_DATABASE_URL',
  'FIREBASE_PROJECT_ID', 'FIREBASE_STORAGE_BUCKET', 'FIREBASE_MESSAGING_SENDER_ID',
  'FIREBASE_APP_ID', 'VAPID_KEY', 'GOOGLE_CLIENT_ID',
  'FAMILY_CALENDAR_ID', 'FAMILY_DRIVE_FOLDER_ID', 'GEOAPIFY_API_KEY'
];

const missing = required.filter(k => !get(k));
if (missing.length) {
  console.error('Missing environment variables:', missing.join(', '));
  console.error('Create a .env file from .env.example or set them in your environment.');
  process.exit(1);
}

// ---- Generate environment.ts (dev) ----
const environmentDev = `// AUTO-GENERATED by scripts/set-env.js — do not edit manually
export const environment = {
  production: false,
  firebase: {
    apiKey: '${get('FIREBASE_API_KEY')}',
    authDomain: '${get('FIREBASE_AUTH_DOMAIN')}',
    databaseURL: '${get('FIREBASE_DATABASE_URL')}',
    projectId: '${get('FIREBASE_PROJECT_ID')}',
    storageBucket: '${get('FIREBASE_STORAGE_BUCKET')}',
    messagingSenderId: '${get('FIREBASE_MESSAGING_SENDER_ID')}',
    appId: '${get('FIREBASE_APP_ID')}'
  },
  vapidKey: '${get('VAPID_KEY')}',
  googleCalendar: {
    apiKey: '${get('FIREBASE_API_KEY')}',
    clientId: '${get('GOOGLE_CLIENT_ID')}',
    discoveryDocs: [
      'https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest',
      'https://www.googleapis.com/discovery/v1/apis/drive/v3/rest'
    ],
    scopes: 'https://www.googleapis.com/auth/calendar https://www.googleapis.com/auth/drive',
    familyCalendarId: '${get('FAMILY_CALENDAR_ID')}',
    familyDriveFolderId: '${get('FAMILY_DRIVE_FOLDER_ID')}'
  },
  geoapifyApiKey: '${get('GEOAPIFY_API_KEY')}'
};
`;

// ---- Generate environment.prod.ts ----
const environmentProd = `// AUTO-GENERATED by scripts/set-env.js — do not edit manually
export const environment = {
  production: true,
  firebase: {
    apiKey: '${get('FIREBASE_API_KEY')}',
    authDomain: '${get('FIREBASE_AUTH_DOMAIN')}',
    databaseURL: '${get('FIREBASE_DATABASE_URL')}',
    projectId: '${get('FIREBASE_PROJECT_ID')}',
    storageBucket: '${get('FIREBASE_STORAGE_BUCKET')}',
    messagingSenderId: '${get('FIREBASE_MESSAGING_SENDER_ID')}',
    appId: '${get('FIREBASE_APP_ID')}'
  },
  vapidKey: '${get('VAPID_KEY')}',
  googleCalendar: {
    apiKey: '${get('FIREBASE_API_KEY')}',
    clientId: '${get('GOOGLE_CLIENT_ID')}',
    discoveryDocs: [
      'https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest',
      'https://www.googleapis.com/discovery/v1/apis/drive/v3/rest'
    ],
    scopes: 'https://www.googleapis.com/auth/calendar https://www.googleapis.com/auth/drive',
    familyCalendarId: '${get('FAMILY_CALENDAR_ID')}',
    familyDriveFolderId: '${get('FAMILY_DRIVE_FOLDER_ID')}'
  },
  geoapifyApiKey: '${get('GEOAPIFY_API_KEY')}'
};
`;

// ---- Generate firebase-messaging-sw.js ----
const serviceWorker = `/* eslint-disable no-undef */
// AUTO-GENERATED by scripts/set-env.js — do not edit manually
importScripts('https://www.gstatic.com/firebasejs/10.14.1/firebase-app-compat.js');
importScripts('https://www.gstatic.com/firebasejs/10.14.1/firebase-messaging-compat.js');

firebase.initializeApp({
  apiKey: '${get('FIREBASE_API_KEY')}',
  authDomain: '${get('FIREBASE_AUTH_DOMAIN')}',
  projectId: '${get('FIREBASE_PROJECT_ID')}',
  storageBucket: '${get('FIREBASE_STORAGE_BUCKET')}',
  messagingSenderId: '${get('FIREBASE_MESSAGING_SENDER_ID')}',
  appId: '${get('FIREBASE_APP_ID')}'
});

const messaging = firebase.messaging();

messaging.onBackgroundMessage((payload) => {
  const data = payload.data || {};
  const title = data.title || 'FamilyApp';
  const options = {
    body: data.body || 'Nouveau message',
    icon: '/assets/icons/icon-192x192.png',
    badge: '/assets/icons/icon-72x72.png',
    data: { url: data.url || '/' }
  };
  self.registration.showNotification(title, options);
  if (navigator.setAppBadge) {
    navigator.setAppBadge();
  }
});

self.addEventListener('notificationclick', (event) => {
  event.notification.close();
  if (navigator.clearAppBadge) {
    navigator.clearAppBadge();
  }
  const url = event.notification.data?.url || '/';
  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      for (const client of windowClients) {
        if (client.url.includes(self.location.origin) && 'focus' in client) {
          client.navigate(url);
          return client.focus();
        }
      }
      return clients.openWindow(url);
    })
  );
});
`;

// ---- Write files ----
const envDir = path.resolve(__dirname, '..', 'src', 'environments');
if (!fs.existsSync(envDir)) fs.mkdirSync(envDir, { recursive: true });

fs.writeFileSync(path.join(envDir, 'environment.ts'), environmentDev);
fs.writeFileSync(path.join(envDir, 'environment.prod.ts'), environmentProd);
fs.writeFileSync(path.resolve(__dirname, '..', 'src', 'firebase-messaging-sw.js'), serviceWorker);

console.log('Environment files generated successfully.');
